-- MySQL Script generated by MySQL Workbench
-- 11/05/15 20:09:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bitacorapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bitacorapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bitacorapp` DEFAULT CHARACTER SET utf8 ;
USE `bitacorapp` ;

-- -----------------------------------------------------
-- Table `bitacorapp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitacorapp`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitacorapp`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitacorapp`.`empresas` (
  `idempresas` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idempresas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitacorapp`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitacorapp`.`projects` (
  `idprojects` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `empresas_idempresas` INT NOT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`idprojects`, `empresas_idempresas`, `user_id_user`),
  INDEX `fk_projects_empresas1_idx` (`empresas_idempresas` ASC),
  INDEX `fk_projects_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_projects_empresas1`
    FOREIGN KEY (`empresas_idempresas`)
    REFERENCES `bitacorapp`.`empresas` (`idempresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `bitacorapp`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitacorapp`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitacorapp`.`task` (
  `idtask` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `time` VARCHAR(45) NULL,
  `taskcol` VARCHAR(45) NULL,
  `projects_idprojects` INT NOT NULL,
  PRIMARY KEY (`idtask`, `projects_idprojects`),
  INDEX `fk_task_projects_idx` (`projects_idprojects` ASC),
  CONSTRAINT `fk_task_projects`
    FOREIGN KEY (`projects_idprojects`)
    REFERENCES `bitacorapp`.`projects` (`idprojects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
